### ISSUE TITLE
Download link contains 'undefined' when the github api call fails due to rate limit

### ISSUE THREAD

**Issue by sangohan** [pragtical/pragtical.github.io#2]
https://api.github.com/repos/pragtical/pragtical/releases/latest is the fetch api that produces the version, which is then used in [here](https://github.com/pragtical/pragtical.github.io/blob/5b56339e997fbab0cb29dcba2c97f4b6326cb6e0/src/components/GetPragtical/index.js#L127) to produce a download link. 

However, the github api can be rate limited, and if that is the case, the link generated will not have a version (but be `undefined`), making it impossible to download.

**Comment by jgmdev** [comment]
Thanks for reporting! Now the latest version is statically embedded on the `GetPragtical` component (which would now require manual updating) but, at least it shouldn't fail now. Hope in the future this can be automated.

**Comment by sangohan** [comment]
you can hard code a version in, but use the api still, and if the api fails (i think it returns a 404 or something), fall back to the hardcoded version - best of both worlds!

**Comment by jgmdev** [comment]
A json file for the website that gets automatically generated with newest released version info would be nice. But that would require some CI inter-repo communication to trigger the required actions. For the moment I will just bump the version number manually each time a new release blog entry is added. But, automation is always welcome!
