### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by SonnyBonds** [pragtical/pragtical.github.io#6]
The invite link to Discord is expired or leads to something with incorrect permissions. This is the error screen:
![bild](https://github.com/user-attachments/assets/89beca84-3450-4c3b-afe1-7831d6a36620)

**Comment by jgmdev** [comment]
Thanks for reporting! Updated the link and made it non-expirable from the discord settings.

Here is the link for reference: https://discord.gg/jAAqT7eYEN
